# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Richard J. Clancy
email: 
description: >- # this means to ignore newlines until "baseurl:"
  #Welcome to my personal website! You can find information about some of my projects, research interests, and past experiences.
#twitter_username: username
github_username: rclancyc
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : #"Richard Clancy"
  avatar : "/assets/images/headshotFI.jpg"
  bio    : "Applied mathematician, \n optimizer, programmer, and data scientist"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rclancyc"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap" 
      url: "https://scholar.google.com/citations?user=Cy9picwAAAAJ&hl"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Richard-Clancy-2"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/richard-j-clancy"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-2593-8623"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rclancyc"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap" 
      url: "https://scholar.google.com/citations?user=Cy9picwAAAAJ&hl"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Richard-Clancy-2"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/richard-j-clancy"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-2593-8623"

collections:
  projects:
    classes: wide
    output: true
    permalink: #/:collection/:path/


defaults:
  # _posts
  #- scope:
  #    path: ""
  #    type: posts
  #  values:
  #    layout: single
  #    author_profile: true
  #    read_time: true
  #    comments: true
  #    share: true
  #    related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      classes: wide
      author_profile: false
      share: true
      excerpt: ""
      sidebar:
        nav: "projects"



# Analytics
analytics:
  provider: "google-gtag"
  google:
    measurement_id: G-EY45K27ZZR
    anonymize_ip: # true, false (default)


#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
